index:
    path: /user
    controller: App\Controller\UserController::index

# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller\UserController::index
#     type: attribute
